import {ITrip} from './tripModel';
import {IPrice} from './priceModel';
import {IScenario} from './scenarioModel';
import {ICost} from './costModel';

export interface ITripDeparture {
    p15_guestdisplayincrement: string;
    statecode: number;
    statecode_desc: string;
    statuscode: number;
    statuscode_desc: string;
    p15_tripid: string;
    p15_tripid_name: string;
    p15_finalpaymentduedate: string;
    p15_paymentscheduleid: string;
    p15_paymentscheduleid_name: string;
    p15_availastemplate: string;
    p15_tourdays: string;
    createdon: string;
    p15_priceunit: number;
    p15_priceunit_desc: string;
    ownerid: string;
    ownerid_name: string;
    modifiedon: string;
    p15_minguests: string;
    p15_departure_guesttypes: string;
    transactioncurrencyid: string;
    transactioncurrencyid_name: string;
    p15_departurecode: string;
    exchangerate: string;
    timezoneruleversionnumber: string;
    p15_availablespaces: string;
    p15_departurereferenceid: string;
    p15_maxguests: string;
    p15_planforleaders: string;
    modifiedby: string;
    modifiedby_name: string;
    modifiedonbehalfby: string;
    modifiedonbehalfby_name: string;
    p15_startdate: string;
    p15_tripdeparturesid: string;
    p15_enddate: string;
    createdonbehalfby: string;
    createdonbehalfby_name: string;
    createdby: string;
    createdby_name: string;
    owningbusinessunit: string;
    owningbusinessunit_name?: null;
    p15_name: string;
    owninguser: string;
    owninguser_name?: null;
    p15_bookedguestcount: string;
    p15_spacesheld: string;
    Trip: ITrip;
    Prices?: (IPrice)[] | null;
    Scenarios?: (IScenario)[] | null;
    Costs?: (ICost)[] | null;
}